repos:
  # Code formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      # Linter
      - id: ruff
        name: ruff-lint
        description: "Run ruff linter"
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
      # Formatter
      - id: ruff-format
        name: ruff-format
        description: "Run ruff formatter"
        types_or: [python, pyi]

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        description: "Remove trailing whitespace"
      - id: end-of-file-fixer
        name: end-of-file-fixer
        description: "Ensure files end with newline"
      - id: check-yaml
        name: check-yaml
        description: "Validate YAML files"
      - id: check-toml
        name: check-toml
        description: "Validate TOML files"
      - id: check-json
        name: check-json
        description: "Validate JSON files"
      - id: check-merge-conflict
        name: check-merge-conflict
        description: "Check for merge conflict markers"
      - id: check-case-conflict
        name: check-case-conflict
        description: "Check for case conflicts"
      - id: mixed-line-ending
        name: mixed-line-ending
        description: "Ensure consistent line endings"

# CI configuration
ci:
  autoupdate_schedule: weekly
  skip: []  # Don't skip any hooks for now
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
